name = "ALDEx2GPU"
uuid = "3a950518-e8ea-43b1-abb0-20cb121e84b1"
authors = ["mpampuch <markpampuch@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
